#!/usr/bin/env bash
#
# Nu plugin wrapper to provide tracing, dumping all input to and output from the plugin 
# into files in the user's home directory
#
# USAGE
#
# Rename this script after the plugin with a _tracer suffix.
# It knows its own name, and looks for the plugin with the corresponding name
# in the same directoryas this script.

plugin_dir=$(dirname "$0")
plugin_name=$(basename "$0" | sed -e 's/_tracer$//')
plugin_path="$plugin_dir/$plugin_name"

in_trace="$HOME/$plugin_name.in"
out_trace="$HOME/$plugin_name.out"

in_fifo="/tmp/$plugin_name.in.$$"
out_fifo="/tmp/$plugin_name.out.$$"

# FIFOs to get PIDs of each stage
mkfifo "$in_fifo"
mkfifo "$out_fifo"
trap 'rm -f $in_fifo $out_fifo' EXIT

tee -a -p "$in_trace" >"$in_fifo" &
in_pid=$!
"$plugin_path" "$@" <"$in_fifo" >"$out_fifo" &
plugin_pid=$!
tee -a -p "$out_trace" <"$out_fifo" &
out_pid=$!

echo >&2 "in tee is $in_pid"
echo >&2 "plugin tee is $plugin_pid"
echo >&2 "out tee is $out_pid"

wait "$plugin_pid"
sleep 10

echo >&2 "plugin is done"
wait "$out_pid"
echo >&2 "out tee is done"
wait "$in_pid"
echo >&2 "in tee is done"
